#!/usr/bin/env python3
"""
Sync terminal colors from configs/common/theme/palette.toml into:
  - configs/common/kitty/colors.generated.conf
  - configs/common/fish/config.d/05-theme-palette.fish
  - configs/common/starship/starship.toml (between ### BEGIN/END GENERATED THEME)

Run from repository root:  python scripts/render_theme.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore[no-redef, unused-ignore]

REPO = Path(__file__).resolve().parents[1]
PALETTE_PATH = REPO / "configs" / "common" / "theme" / "palette.toml"
KITTY_OUT = REPO / "configs" / "common" / "kitty" / "colors.generated.conf"
FISH_OUT = REPO / "configs" / "common" / "fish" / "config.d" / "05-theme-palette.fish"
STARSHIP_PATH = REPO / "configs" / "common" / "starship" / "starship.toml"

STARSHIP_BEGIN = "### BEGIN GENERATED THEME (configs/common/theme/palette.toml)"
STARSHIP_END = "### END GENERATED THEME (configs/common/theme/palette.toml)"

# fish_color_* ← starship_palette key (semantic link)
FISH_FROM_PALETTE: list[tuple[str, str]] = [
    ("fish_color_normal", "white1"),
    ("fish_color_command", "cyan_bright"),
    ("fish_color_param", "blue1"),
    ("fish_color_redirection", "magenta_bright"),
    ("fish_color_comment", "gray5"),
    ("fish_color_error", "red_bright"),
    ("fish_color_end", "green_bright"),
    ("fish_color_operator", "yellow_bright"),
    ("fish_color_quote", "green_dim"),
    ("fish_color_autosuggestion", "gray4"),
    ("fish_color_cancel", "red_dim"),
    ("fish_color_match", "cyan_base"),
    ("fish_color_search_match", "yellow_base"),
    ("fish_color_selection", "white0_reduce_blue"),
    ("fish_pager_color_progress", "gray4"),
    ("fish_pager_color_prefix", "cyan_bright"),
    ("fish_pager_color_completion", "white1"),
    ("fish_pager_color_description", "gray5"),
]


def load_palette() -> dict:
    data = tomllib.loads(PALETTE_PATH.read_text(encoding="utf-8"))
    if "kitty" not in data or "starship_palette" not in data:
        sys.exit("palette.toml must contain [kitty] and [starship_palette] tables")
    return data


def render_kitty(kitty: dict[str, str]) -> str:
    lines = [
        "# AUTO-GENERATED by scripts/render_theme.py — source: configs/common/theme/palette.toml",
        "# Do not edit by hand; run: python scripts/render_theme.py",
        "",
    ]
    first = [
        "background",
        "foreground",
        "cursor",
        "cursor_text_color",
        "selection_background",
        "selection_foreground",
    ]
    for key in first:
        if key in kitty:
            lines.append(f"{key} {kitty[key]}")
    rest = [k for k in kitty if k not in first]

    def sort_key(k: str) -> tuple:
        m = re.match(r"^color(\d+)$", k)
        if m:
            return (0, int(m.group(1)))
        return (1, k)

    for key in sorted(rest, key=sort_key):
        lines.append(f"{key} {kitty[key]}")
    return "\n".join(lines) + "\n"


def render_fish(starship_palette: dict[str, str]) -> str:
    lines = [
        "# AUTO-GENERATED by scripts/render_theme.py — source: configs/common/theme/palette.toml",
        "# Do not edit by hand; run: python scripts/render_theme.py",
        "status is-interactive; or return",
        "",
    ]
    for fish_var, pal_key in FISH_FROM_PALETTE:
        hexv = starship_palette.get(pal_key)
        if not hexv:
            continue
        # fish treats # as comment unless quoted
        lines.append(f"set -g {fish_var} '{hexv}'")
    lines.append("")
    return "\n".join(lines)


def render_starship_palette_block(starship_palette: dict[str, str]) -> str:
    lines = ["[palettes.nordic]"]
    for key in sorted(starship_palette.keys()):
        val = starship_palette[key].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{key} = "{val}"')
    return "\n".join(lines) + "\n"


def splice_starship(generated_block: str) -> None:
    text = STARSHIP_PATH.read_text(encoding="utf-8")
    if STARSHIP_BEGIN in text and STARSHIP_END in text:
        pattern = re.compile(
            re.escape(STARSHIP_BEGIN) + r".*?" + re.escape(STARSHIP_END),
            re.DOTALL,
        )
        replacement = STARSHIP_BEGIN + "\n" + generated_block.rstrip("\n") + "\n" + STARSHIP_END
        new_text, n = pattern.subn(replacement, text, count=1)
        if n != 1:
            sys.exit("Failed to splice starship.toml (markers found but replace failed)")
        STARSHIP_PATH.write_text(new_text, encoding="utf-8", newline="\n")
        return

    # Insert before EOF if no markers yet
    if "[palettes.nordic]" in text and STARSHIP_BEGIN not in text:
        sys.exit(
            "starship.toml contains [palettes.nordic] but no theme markers. "
            "Run once: add markers around [palettes.nordic] or use a fresh starship.toml from the repo."
        )
    sys.exit("starship.toml: add markers:\n" + STARSHIP_BEGIN + "\n...\n" + STARSHIP_END)


def main() -> None:
    data = load_palette()
    kitty = {k: str(v) for k, v in data["kitty"].items()}
    starship_palette = {k: str(v) for k, v in data["starship_palette"].items()}

    KITTY_OUT.parent.mkdir(parents=True, exist_ok=True)
    KITTY_OUT.write_text(render_kitty(kitty), encoding="utf-8", newline="\n")

    FISH_OUT.parent.mkdir(parents=True, exist_ok=True)
    FISH_OUT.write_text(render_fish(starship_palette), encoding="utf-8", newline="\n")

    block = render_starship_palette_block(starship_palette)
    splice_starship(block)
    print(f"Wrote {KITTY_OUT.relative_to(REPO)}")
    print(f"Wrote {FISH_OUT.relative_to(REPO)}")
    print(f"Updated {STARSHIP_PATH.relative_to(REPO)} palette block")


if __name__ == "__main__":
    main()
