# AUTO-GENERATED by scripts/render_theme.py — source: configs/common/theme/palette.toml
# Do not edit by hand; run: python scripts/render_theme.py
status is-interactive; or return

set -g fish_color_normal '#cdd4e1'
set -g fish_color_command '#6cd9e8'
set -g fish_color_param '#61afef'
set -g fish_color_redirection '#d896ff'
set -g fish_color_comment '#7d8798'
set -g fish_color_error '#ff7b86'
set -g fish_color_end '#a9dc76'
set -g fish_color_operator '#ffd866'
set -g fish_color_quote '#82ad66'
set -g fish_color_autosuggestion '#5c6370'
set -g fish_color_cancel '#c9565f'
set -g fish_color_match '#56b6c2'
set -g fish_color_search_match '#e5c07b'
set -g fish_color_selection '#a9b2c3'
set -g fish_pager_color_progress '#5c6370'
set -g fish_pager_color_prefix '#6cd9e8'
set -g fish_pager_color_completion '#cdd4e1'
set -g fish_pager_color_description '#7d8798'
