# AUTO-GENERATED by scripts/render_theme.py — source: configs/common/theme/palette.toml
# Do not edit by hand; run: python scripts/render_theme.py
status is-interactive; or return

set -g fish_color_normal '#cad3f5'
set -g fish_color_command '#9addd3'
set -g fish_color_param '#8aadf4'
set -g fish_color_redirection '#f7c9eb'
set -g fish_color_comment '#8087a2'
set -g fish_color_error '#f095a3'
set -g fish_color_end '#b4e0a5'
set -g fish_color_operator '#f0dcaf'
set -g fish_color_quote '#98d485'
set -g fish_color_autosuggestion '#6e738d'
set -g fish_color_cancel '#e56d7e'
set -g fish_color_match '#8bd5ca'
set -g fish_color_search_match '#eed49f'
set -g fish_color_selection '#b5bdd9'
set -g fish_pager_color_progress '#6e738d'
set -g fish_pager_color_prefix '#9addd3'
set -g fish_pager_color_completion '#cad3f5'
set -g fish_pager_color_description '#8087a2'
