# AUTO-GENERATED by scripts/render_theme.py — source: configs/common/theme/palette.toml
# Do not edit by hand; run: python scripts/render_theme.py
status is-interactive; or return

set -g fish_color_normal '#D8DEE9'
set -g fish_color_command '#9FC6C5'
set -g fish_color_param '#81A1C1'
set -g fish_color_redirection '#BE9DB8'
set -g fish_color_comment '#60728A'
set -g fish_color_error '#C5727A'
set -g fish_color_end '#B1C89D'
set -g fish_color_operator '#EFD49F'
set -g fish_color_quote '#97B67C'
set -g fish_color_autosuggestion '#4C566A'
set -g fish_color_cancel '#B74E58'
set -g fish_color_match '#8FBCBB'
set -g fish_color_search_match '#EBCB8B'
set -g fish_color_selection '#C0C8D8'
set -g fish_pager_color_progress '#4C566A'
set -g fish_pager_color_prefix '#9FC6C5'
set -g fish_pager_color_completion '#D8DEE9'
set -g fish_pager_color_description '#60728A'
